### ISSUE TITLE
Feature request: Customization options for counsel-gtags--update-tags-command

### ISSUE THREAD

**Issue by diamond-lizard** [syohex/emacs-counsel-gtags#21]
I'd like to be able to select the command that's run to update the gtags database.  This is useful because I'd like to tell gtags to use idtools (via the "--idutils" option), for example.. or maybe pass it some other options in the future.

It would be nice if this ability to change how the gtags database is update was exposed in the Counsel Gtags customization group, rather than requiring editing the hardcoded values in the source.

**Comment by syohex** [comment]
This package is no longer maintained. If you have an issue, please send it to https://github.com/FelipeLema/emacs-counsel-gtags
