### ISSUE TITLE
counsel-gtags-dwim fails in Cygwin

### ISSUE THREAD

**Issue by kenhuang-io** [syohex/emacs-counsel-gtags#23]
Hi,

counsel-gtags has a bug when do `counsel-gtags-dwim` to find definition in Cygwin,
it will complain that global exits with -1 in the echo area.
After adding some debug messages, I guess it's caused by passing absolute file name to `--from-here` of `global`.

To prove my guess, I've tried it in below Cygwin shell session,
with a demo project `foo` including foo.cpp and bar.cpp.
`~/sf_svn` is a symbolic link to `/cygdrive/d/svn/`, `$HOME` is `/cygdrive/d/tools/home/`,
`pwd` is `~/sf_svn/foo`, and tag files are located in `~/sf_svn/foo`.

    PC0 ~/sf_svn/foo
    $ global --result=grep --from-here=81:~/sf_svn/foo/foo.cpp load
    global: path name in the context is not found.

    PC0 ~/sf_svn/foo
    $ global --result=grep --from-here=81:/cygdrive/d/svn/foo/foo.cpp load
    global: '/cygdrive/d/svn/foo/foo.cpp' is out of the source project.

    PC0 ~/sf_svn/foo
    $ global --result=grep --from-here=81:$HOME/sf_svn/foo/foo.cpp load
    global: '/cygdrive/d/tools/home/sf_svn/foo/foo.cpp' is out of the source project.

    PC0 ~/sf_svn/foo
    $ global --result=grep --from-here=81:foo.cpp load
    bar.cpp:98:load()
    
so I think maybe it'll be better to pass relative file path to `--from-here`?

Thanks.

**Comment by kenhuang-io** [comment]
It fails to work on Linux too for this specific case.

**Comment by syohex** [comment]
This package is no longer maintained. If you have an issue, please send it to https://github.com/FelipeLema/emacs-counsel-gtags
