### ISSUE TITLE
counsel-gtags adoption

### ISSUE THREAD

**Issue by Ergus** [syohex/emacs-counsel-gtags#33]
Hi:

@FelipeLema is willing to adopt this package. 

He has done an exelent work in his [fork](https://github.com/FelipeLema/emacs-counsel-gtags) recently. 

He has updated the package adding support for tramp and other corrections. And using the new features and improves in `counsel` and `ivy`. As the package has not been updated in the last 3 years maybe you could redirect the link in melpa to his fork?

Very thanks in advance.

**Comment by xuhdev** [comment]
This has already been done: https://github.com/melpa/melpa/blob/master/recipes/counsel-gtags

**Comment by Ergus** [comment]
Yes but for some reason the package-list-packages documentation still shows this link.

![image](https://user-images.githubusercontent.com/6975176/64488913-b0152000-d24d-11e9-97dd-95490d70f147.png)
