### ISSUE TITLE
[multiwindow] counsel-gtags-dwim will jump to another window

### ISSUE THREAD

**Issue by bernarcio** [syohex/emacs-counsel-gtags#34]
Symptom:
Window vertically split, upper as A, and lower as B,
Source code in window A, and other files open in B;
if using counsel-gtags-dwim to jump to the symbol in A, it will display in window B, and if jumping again, everything will only happen in window B, unless you open other files in window A.

So the question is, how to prevent it from jumping to another window? Because that window is supposed to be used for note-taking, or something like that.

Thanks a lot!

**Comment by hnmurz** [comment]
Did you find an solution for this problem?

**Comment by syohex** [comment]
This package is no longer maintained. If you have an issue, please send it to https://github.com/FelipeLema/emacs-counsel-gtags
