### ISSUE TITLE
counsel-gtags should filter/prevent color codes

### ISSUE THREAD

**Issue by jgarvin** [syohex/emacs-counsel-gtags#35]
I assume gtags or global are producing output with colors in it, because when I try to find defintions I'm seeing this:

`(1/1) Find Definition: self_only_test

[30;43mself_only_test[0m[K`

Then when I hit enter to pick the definition global complains "invalid regular expression" probably because of those brackets.

I checked my environment and I don't have any GREP_COLORS set (global --help mentions it respects this var).

I checked with `C-h v` for plausible looking vars for customizing the gtags/global commands but didn't see any.

My global version is a little old, 6.5.6.

**Comment by jgarvin** [comment]
After digging though counsel-gtags.el I saw it was using grep, so I tried:

(setq counsul-grep-command "grep --color=never")

Which did the trick. I also discovered my bashrc sets an alias to enable color for grep -- but that would only be an issue if counsel runs the commands inside a shell, not sure if it does.

**Comment by jgarvin** [comment]
...Strangely on emacs restart this came back, not sure why. Now these have no effect on the problem:

(setq grep-find-command "grep --color=never")
(setq counsul-grep-command "grep --color=never")

**Comment by syohex** [comment]
This package is no longer maintained. If you have an issue, please send it to https://github.com/FelipeLema/emacs-counsel-gtags
