### ISSUE TITLE
Error in post-command-hook (ivy--queue-exhibit): (wrong-number-of-arguments (1 . 2) 0)

### ISSUE THREAD

**Issue by mihaipop11** [syohex/emacs-counsel-gtags#36]
`Error in post-command-hook (ivy--queue-exhibit): (wrong-number-of-arguments (1 . 2) 0)`
shows up when want to use any of the following commands:

```
"M-x counsel-gtags-find-definition <RET>"
"M-x counsel-gtags-find-symbol <RET>"
"M-x counsel-gtags-find-reference <RET>"
```

I am using these versions:

- ivy `20191128.1153`
- swiper `20191128.1126`
- counsel `20191127.1747`
- counsel-gtags `20191119.1243`

and my setup is the following:

```
(use-package counsel
  :ensure t
  :bind*
  (("M-x" . counsel-M-x)
   ("C-c C-m" . counsel-M-x)
   ("C-x C-m" . counsel-M-x)
   ("C-x m" . counsel-M-x)
   ("C-x C-f" . counsel-find-file))
  :custom
  (counsel-find-file-ignore-regexp "\\.DS_Store\\|.git"))

(use-package counsel-gtags
  ;; :disabled
  :ensure t
  :init
  (add-hook 'c-mode-common-hook
            (lambda ()
              (when (derived-mode-p 'c-mode 'c++-mode 'java-mode 'asm-mode)
                (counsel-gtags-mode t))))
  :config
  (setq counsel-gtags-auto-update t
        counsel-gtags-path-style 'root
        )
  :bind (:map
         counsel-gtags-mode-map
         ("M-." . counsel-gtags-dwim)
         ("M-," . counsel-gtags-go-backward))
  )

(use-package swiper
  :ensure t
  :bind (("C-s" . swiper)
         ;; ("M-*" . swiper-under-point)
         ))

(use-package ivy
  :ensure t
  :bind (("C-c C-r" . ivy-resume)
         ("C-s" . swiper-isearch)
         ("M-x" . counsel-M-x))
  :config
  (ivy-mode t)
  (setq ivy-use-virtual-buffers t)
  (setq enable-recursive-minibuffers t))
```

Am i doing something wrong or this is really a bug?

**Comment by kenhuang-io** [comment]
`M-x toggle-debug-on-error` to enable debugging, it will show you the calling stack, which can help find the problem.

**Comment by mihaipop11** [comment]
something looks fishy here, the call stack is not showing up, and more than this, the issue seems to be from ivy/swiper actually, it shows up before the commands i'm trying to execute are invoked. I will investigate this a bit more

**Comment by mihaipop11** [comment]
just as an update, if i use counsel-gtags from melpa-stable the issue is gone

**Comment by syohex** [comment]
This package is no longer maintained. If you have an issue, please send it to https://github.com/FelipeLema/emacs-counsel-gtags
