### ISSUE TITLE
Publish to MEPLA

### ISSUE THREAD

**Issue by rakanalh** [syohex/emacs-counsel-gtags#6]
Hello,

Would be nice if this is available on MEPLA.

Thanks

**Comment by syohex** [comment]
https://github.com/melpa/melpa/pull/4428

I have sent PR.

**Comment by purcell** [comment]
I can't help with getting this in MEPLA, but it's in MELPA now at least! ;-)

Packages will start building in the next few hours.

**Comment by rakanalh** [comment]
Thanks guys! closing ticket.
