### ISSUE TITLE
Directly jump to definition/reference for a single candidate

### ISSUE THREAD

**Issue by Gleek** [syohex/emacs-counsel-gtags#7]
Is it possible to directly jump to the definition of the function than listing the filename first in `counsel-gtags-dwim`/ `counsel-gtags-find-definition`? 
This should make navigation faster.

**Comment by syohex** [comment]
I don't understand yet. I suppose ivy/counsel does not provides such feature.

> This should make navigation faster.

I think so.

**Comment by lpenz** [comment]
`counsel-gtags-find-definition`/`reference` loads the entire tag database incrementally until it finds a match. So, if you have a huge database and you're looking for something that starts with a "z", you'll have to wait for a while.
If it loaded only things that started with that first letter, the operation would already be 20x faster.

**Comment by Gleek** [comment]
Closing this as https://github.com/syohex/emacs-counsel-gtags/pull/13 has already fixed this
